services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
