import type {
  MainCategoryApiItem,
  MenuProductApiItem,
  MenuProfileApiItem,
} from "@/lib/api";

const PREVIEW_MENU_ID = 0;

export const MENU_THEME_PREVIEW_MENU: MenuProfileApiItem = {
  menuId: PREVIEW_MENU_ID,
  qrId: 0,
  publicId: "preview",
  userId: 0,
  themeId: "luxury",
  businessName: "LUXURY DINING",
  slogan: "Mevsimin en taze malzemeleriyle hazırlanan modern mutfak.",
  chefDisplayName: "Akıllı Şef",
  chefAvatarKey: "default",
  logoUrl: null,
  phone: "+90 555 000 0000",
  email: "hello@luxury.dining",
  address: "İstanbul",
  publicUrl: "/menu/preview",
  active: true,
};

export const MENU_THEME_PREVIEW_CATEGORIES: MainCategoryApiItem[] = [
  {
    id: 1,
    slug: "baslangiclar",
    name: "Başlangıçlar",
    sortOrder: 1,
    subs: [
      { id: 11, mainCategoryId: 1, slug: "sicak", name: "Sıcak", sortOrder: 1 },
      { id: 12, mainCategoryId: 1, slug: "soguk", name: "Soğuk", sortOrder: 2 },
    ],
  },
  {
    id: 2,
    slug: "ana-yemekler",
    name: "Ana Yemekler",
    sortOrder: 2,
    subs: [
      {
        id: 21,
        mainCategoryId: 2,
        slug: "deniz-urunleri",
        name: "Deniz Ürünleri",
        sortOrder: 1,
      },
    ],
  },
  {
    id: 3,
    slug: "tatlilar",
    name: "Tatlılar",
    sortOrder: 3,
    subs: [
      { id: 31, mainCategoryId: 3, slug: "cikolatali", name: "Çikolatalı", sortOrder: 1 },
      { id: 32, mainCategoryId: 3, slug: "meyveli", name: "Meyveli", sortOrder: 2 },
    ],
  },
  {
    id: 4,
    slug: "icecekler",
    name: "İçecekler",
    sortOrder: 4,
    subs: [
      { id: 41, mainCategoryId: 4, slug: "kokteyller", name: "Kokteyller", sortOrder: 1 },
      {
        id: 42,
        mainCategoryId: 4,
        slug: "sicak-icecekler",
        name: "Sıcak İçecekler",
        sortOrder: 2,
      },
    ],
  },
];

export const MENU_THEME_PREVIEW_PRODUCTS: MenuProductApiItem[] = [
  {
    productId: 101,
    menuId: PREVIEW_MENU_ID,
    name: "Wagyu Carpaccio",
    description: "Thinly sliced wagyu with crispy capers and microgreens.",
    price: 28,
    currency: "TRY",
    subCategoryId: 11,
    subCategorySlug: "sicak",
    subCategoryName: "Sıcak",
    mainCategoryId: 1,
    mainCategorySlug: "baslangiclar",
    mainCategoryName: "Başlangıçlar",
    sortOrder: 1,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAByiirPvmNcq4AaCOe97vX0-gpTn-EBQsRfJLtu9iI_H1iQmDsFvMPWLDq2HArzajhH-JXDA9YAnJLt9YHi5zozaWCPld8Kk27Vr2MxNIu_SKkXyDb_zkvZQX8fSSp_rnXoS3n47flDC3SWOgcMTYY4VOw-GnvJY4okD4_fC2-vaerOUEQmCs7i-pj9jyoBEKi2AzBBCnHVmtCzWRmScwf3cpH1lMyPJy8Aa62gJ3cwVZOUvUIPkGM4t1AOyseoXyyeKz636c9fDMA",
    available: true,
  },
  {
    productId: 102,
    menuId: PREVIEW_MENU_ID,
    name: "Heirloom Tomato Tart",
    description: "Seasonal tomatoes on a delicate pastry shell with basil oil.",
    price: 22,
    currency: "TRY",
    subCategoryId: 12,
    subCategorySlug: "soguk",
    subCategoryName: "Soğuk",
    mainCategoryId: 1,
    mainCategorySlug: "baslangiclar",
    mainCategoryName: "Başlangıçlar",
    sortOrder: 2,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDHP7xWtTAXPdlGlU1imuL5lpc8Gn0txL78ZowOyaL9Bgkf2fzzWQEYq_gt5xIAD6Zc19sRnDZ1lantZMkWJ1bLdlpPiCndr3ZD4b45h4ca-YfMh3ZTzVZdm6l7XXx7TYMsfGfaaravAix0r3vEzY9WEWNHWvaDWL5ogDAvYgahDEWXwBD87dtP7gAmP3-rHdEv52ZFOesVJy6NWPR4xhIc5FA6nrvIcAJTgqu3tBJPTcsMWEJvCD6ng_2bdbwI3nnz5qGMlF4uLT14",
    available: true,
  },
  {
    productId: 201,
    menuId: PREVIEW_MENU_ID,
    name: "Signature Grilled Salmon",
    description:
      "Sourced from the pristine waters of the North Atlantic. Hand-selected for its marbling, elevated by cedar smoke and a house-made citrus reduction.",
    price: 34,
    currency: "TRY",
    subCategoryId: 21,
    subCategorySlug: "deniz-urunleri",
    subCategoryName: "Deniz Ürünleri",
    mainCategoryId: 2,
    mainCategorySlug: "ana-yemekler",
    mainCategoryName: "Ana Yemekler",
    sortOrder: 1,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuATPKdaaYvSsDAdngH_KKpekZlWHlIDfPx4cyIE1JDeHwf9YFZOcGX5J9iHh-uxnH0pOhNYwGY6O0i6cchfJ6g9MaZs65WfP5fFy0A7nJzlARsbUvCssDjwtqu84O3OzZSG0eTEVxOVq6hZ6gvGzuXHh1qtt-WE-HSoTkuHFr9LI0tdqp9c-QUGg0gZLA5SD8LxrmFeSBhyiXX6c5Qd6X7qT6Gwxj2Iv5Us8WuQgMgD-I970GiDKVeZM71ekYNeAAiJ_g4QwozHnLhB",
    available: true,
    nutrition: {
      basis: "PER_100G",
      energyKj: 1757,
      energyKcal: 420,
      fat: 22,
      saturatedFat: 5.2,
      carbohydrate: 4,
      sugars: 1.5,
      fibre: 0.8,
      protein: 38,
      salt: 0.45,
      otherNutrients: [
        { name: "Omega-3", value: 1.2, unit: "g" },
      ],
    },
  },
  {
    productId: 202,
    menuId: PREVIEW_MENU_ID,
    name: "Pan-Seared Sea Bass",
    description: "Sea bass fillet atop creamy saffron risotto with lemon reduction.",
    price: 42,
    currency: "TRY",
    subCategoryId: 21,
    subCategorySlug: "deniz-urunleri",
    subCategoryName: "Deniz Ürünleri",
    mainCategoryId: 2,
    mainCategorySlug: "ana-yemekler",
    mainCategoryName: "Ana Yemekler",
    sortOrder: 2,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuC6QUQaFtsI_YqyFqPGQh31ZqNdPx2-Qz7daCpoFJHUECKDNDcD1vYpocYPUaO6Ruo46SDf5ysLexh0R65iS3m6I-ZkMg9QFK7maNsqG6zDoYs1QHf-vxtARP3FHkXCcUyCc80Y0aQSXZHVwqIKWil9OMl--nOxBoWk66ypDe_l6SQzRLsKXut9wtU2CaBL3f92TFCGgbFXMfdEIxirzyC_s7stJvvt6Hb9C9kasStpvrLwo6NKp80qsvoVdM6JDPLeymbw9Ow89To2",
    available: true,
  },
  {
    productId: 301,
    menuId: PREVIEW_MENU_ID,
    name: "Dark Chocolate Sphere",
    description: "Gold leaf accents with raspberry coulis on matte black porcelain.",
    price: 18,
    currency: "TRY",
    subCategoryId: 31,
    subCategorySlug: "cikolatali",
    subCategoryName: "Çikolatalı",
    mainCategoryId: 3,
    mainCategorySlug: "tatlilar",
    mainCategoryName: "Tatlılar",
    sortOrder: 1,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuB4syMM9PZnOcdIlD1weNmy7UiLxGrjBCGWg9QRkGNKuQkFEdIfOXbJSAgM_Uadd6GYDQRw37HHHV4Ko4SMyv-aBaNuPztkMth_m7qcbt1_LXfVCayDDfEARg_dSaeh9u3BpOu35FHTXQVrPpWioCN-nFntypdjrs7s7GEd3tt8XdDG9bXQA127eZwZXZ7B-zLI2z0RVeb8I-CgBJsCvW_YveNi0EwbGJyH88nMwuPj_GEDQCtLj04rbJZY-of60x4bu9JFig88FDdB",
    available: true,
  },
  {
    productId: 302,
    menuId: PREVIEW_MENU_ID,
    name: "Vanilla Bean Panna Cotta",
    description: "Silky panna cotta with seasonal berry compote.",
    price: 16,
    currency: "TRY",
    subCategoryId: 32,
    subCategorySlug: "meyveli",
    subCategoryName: "Meyveli",
    mainCategoryId: 3,
    mainCategorySlug: "tatlilar",
    mainCategoryName: "Tatlılar",
    sortOrder: 2,
    available: true,
  },
  {
    productId: 401,
    menuId: PREVIEW_MENU_ID,
    name: "Craft Garden Cocktail",
    description: "Fresh mint, dehydrated citrus, and house botanical syrup.",
    price: 14,
    currency: "TRY",
    subCategoryId: 41,
    subCategorySlug: "kokteyller",
    subCategoryName: "Kokteyller",
    mainCategoryId: 4,
    mainCategorySlug: "icecekler",
    mainCategoryName: "İçecekler",
    sortOrder: 1,
    imageUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDF1CpzVLOnPN0hQRFnwLGFb6-_R5OnifpCWrwc7VtI4mzzvzyoLZchow2mCP6-z9m2bLMoygJhNtbhsWV2oF4ZpnwVTN3L5RMUVlxTbogOEK2hawdICXkS66GuE7dWt6AqNrZjnNUv-0Ja8FnME_Mdc2gmIWueKNvJCkMDU_7OKeN27JU3xdAjWjydypGtsKCEDl3qh6wc0w8eC4TUKiNWHC3LhtRIelUJZl2nb9CYDZHnOnzhkwcfZ5ZKWGK7HNFeiE6OXuKn7Mvh",
    available: true,
  },
  {
    productId: 402,
    menuId: PREVIEW_MENU_ID,
    name: "Single-Origin Espresso",
    description: "Bright acidity with notes of cocoa and citrus.",
    price: 8,
    currency: "TRY",
    subCategoryId: 42,
    subCategorySlug: "sicak-icecekler",
    subCategoryName: "Sıcak İçecekler",
    mainCategoryId: 4,
    mainCategorySlug: "icecekler",
    mainCategoryName: "İçecekler",
    sortOrder: 2,
    available: true,
  },
];
